# Generated by Django 6.0.6 on 2026-09-04 04:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_activitylog_options_activitylog_ip_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Cierre')),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Inicial')),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Final')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10, verbose_name='Estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Turno de Caja',
                'verbose_name_plural': 'Turnos de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
    ]
