# Generated by Django 6.0.6 on 2026-09-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_turnocaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Impulso Smart', max_length=100)),
                ('color_primario', models.CharField(default='#4318ff', max_length=7)),
                ('modo_oscuro', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
            },
        ),
    ]
