# Generated by Django 5.2.8 on 2026-04-23 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyclose',
            name='closed_by',
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Apertura')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Cierre')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Inicial')),
                ('total_sales_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ventas Efectivo')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Egresos')),
                ('expected_final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Final Esperado')),
                ('real_final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Final Real')),
                ('is_open', models.BooleanField(default=True, verbose_name='¿Caja Abierta?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Arqueo de Caja',
                'verbose_name_plural': 'Arqueos de Caja',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CashExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('description', models.CharField(max_length=255, verbose_name='Concepto')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.cashsession')),
            ],
        ),
        migrations.DeleteModel(
            name='CashMovement',
        ),
        migrations.DeleteModel(
            name='DailyClose',
        ),
    ]
