# Generated by Django 5.2.8 on 2026-05-11 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_dailyclose_closed_by_cashsession_cashexpense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='initial_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Inicial'),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='real_final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Final Real'),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Egresos'),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='total_sales_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ventas Efectivo'),
        ),
    ]
