# Generated by Django 5.2.8 on 2026-05-11 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_cashexpense_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsession',
            name='total_sales_digital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ventas Digital/Otros'),
        ),
    ]
