# Generated by Django 5.2.8 on 2026-04-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_create_default_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Deudor'),
        ),
    ]
