# Generated by Django 5.2.8 on 2026-04-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Puntos Acumulados'),
        ),
    ]
