# Generated by Django 5.2.8 on 2026-05-06 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_create_default_customer_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('DEBIT', 'Tarjeta de Débito'), ('CREDIT', 'Tarjeta de Crédito'), ('TRANS', 'Transferencia')], default='CASH', max_length=10, verbose_name='Método de Pago')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notas')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.customer', verbose_name='Cliente')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pago de Cliente',
                'verbose_name_plural': 'Pagos de Clientes',
                'ordering': ['-date'],
            },
        ),
    ]
