# Generated by Django 5.2.8 on 2026-05-11 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_balance_alter_customer_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('entry_type', models.CharField(choices=[('DEBT', 'Deuda (Venta)'), ('CREDIT', 'Crédito (Pago)')], max_length=10, verbose_name='Tipo de Entrada')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia (Venta/Pago #)')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Resultante')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_ledger', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cuenta Corriente',
                'verbose_name_plural': 'Movimientos de Cuenta Corriente',
                'ordering': ['-date'],
            },
        ),
    ]
