# Generated by Django 5.2.8 on 2026-05-13 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_payment_method_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Límite de Crédito'),
        ),
    ]
