# Generated by Django 5.2.8 on 2026-04-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CC', 'Cuenta Corriente')], default='CASH', max_length=10, verbose_name='Método de Pago'),
        ),
    ]
