# Generated by Django 5.2.8 on 2026-05-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CC', 'Cuenta Corriente'), ('DEBIT', 'Tarjeta de Débito'), ('CREDIT', 'Tarjeta de Crédito'), ('TRANS', 'Transferencia')], default='CASH', max_length=10, verbose_name='Método de Pago'),
        ),
    ]
