# Generated by Django 5.2.8 on 2026-05-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='sale',
            name='surcharge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Recargo'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto IVA'),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto IVA'),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='Tasa de IVA (%)'),
        ),
    ]
