# Generated by Django 5.2.8 on 2026-05-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_discount_amount_sale_surcharge_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='cost_price_at_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Costo (Histórico)'),
        ),
    ]
