# Generated by Django 5.2.8 on 2026-05-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_barcode_alter_product_sku_and_more'),
        ('sales', '0008_salereturn_salereturndetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='points_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento por Puntos'),
        ),
        migrations.AddField(
            model_name='sale',
            name='points_redeemed',
            field=models.IntegerField(default=0, verbose_name='Puntos Canjeados'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Promo')),
                ('promo_type', models.CharField(choices=[('PERCENT', 'Descuento Porcentual (%)'), ('FIXED_QTY', 'Precio Fijo por Cantidad (Ej: 2x1)'), ('DAY_DISCOUNT', 'Descuento por Día de la Semana')], max_length=20, verbose_name='Tipo de Promo')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje Descuento')),
                ('fixed_qty', models.IntegerField(default=0, verbose_name='Cantidad Requerida (Ej: 2)')),
                ('fixed_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Total del Pack')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True, verbose_name='Día de Aplicación')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha Fin')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='products.category', verbose_name='Categorías Incluidas')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='products.product', verbose_name='Productos Incluidos')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
            },
        ),
    ]
