# Generated by Django 5.2.8 on 2026-05-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_points_discount_sale_points_redeemed_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='promo_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento por Promos'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento Manual'),
        ),
    ]
