# Generated by Django 6.0.6 on 2026-09-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_sale_promo_discount_alter_sale_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Peso (kg)'),
        ),
    ]
