# Generated by Django 6.0.6 on 2026-09-03 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_saledetail_peso_kg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='date',
        ),
        migrations.AddField(
            model_name='sale',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 3, 1, 18, 15, 300932, tzinfo=datetime.timezone.utc), verbose_name='Fecha y Hora'),
            preserve_default=False,
        ),
    ]
