# Generated by Django 6.0.6 on 2026-09-04 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_turnocaja'),
        ('sales', '0012_alter_sale_options_remove_sale_date_sale_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.turnocaja', verbose_name='Turno de Caja'),
        ),
    ]
