# Generated by Django 5.2.8 on 2026-05-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_pricelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='000000', max_length=50, unique=True, verbose_name='SKU / Código de Barras'),
        ),
    ]
