# Generated by Django 5.2.8 on 2026-05-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_purchase_purchasedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='Tasa de IVA (%)'),
        ),
    ]
