# Generated by Django 5.2.8 on 2026-05-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_pricelist_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='000000', max_length=50, unique=True, verbose_name='SKU Interno'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ORDERED', 'Pedido'), ('RECEIVED', 'Recibido (Stock sumado)'), ('PAID', 'Pagado (Impacta Caja)'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=10, verbose_name='Estado'),
        ),
    ]
