# Generated by Django 5.2.8 on 2026-05-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_barcode_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('lt', 'Litro'), ('m', 'Metro'), ('caja', 'Caja'), ('paquete', 'Paquete')], default='unidad', max_length=10, verbose_name='Unidad'),
        ),
    ]
