# Generated by Django 6.0.6 on 2026-09-05 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_peso_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock'),
        ),
    ]
